spring:
  application:
    name: backend

  jpa:
    generate-ddl: true
    database: postgresql
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms?characterEncoding=UTF-8
    username: postgres
    password: popost

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081
  servlet:
    context-path: /api